parameters:
  UserId:
    name: userId
    in: path
    required: true
    description: The ID of the user to retrieve.
    schema:
      type: string
  AuthToken:
    name: Authorization
    in: header
    required: true
    description: The token required for authentication.
    schema:
      type: string
  Page:
    name: page
    in: query
    required: false
    description: The page number for pagination.
    schema:
      type: integer
      default: 1
  Limit:
    name: limit
    in: query
    required: false
    description: The number of items to return per page.
    schema:
      type: integer
      default: 10