openapi: 3.0.0
info:
  title: API Documentation
  description: This is the API documentation for the backend application.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Development server
paths:
  /auth:
    $ref: './paths/auth.yaml'
  /users:
    $ref: './paths/users.yaml'
components:
  schemas:
    $ref: './components/schemas.yaml'
  responses:
    $ref: './components/responses.yaml'
  parameters:
    $ref: './components/parameters.yaml'